config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  resources :raffles, :path_names => {:edit => 'enter' }
  resources :tickets, :path_names => {:edit => 'claim' }

  resources :raffles do
    resources :users, only: [:index]
  end

  resources :user do
    resources :tickets, only: [:new]
  end

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  root 'welcome#home'
  get '/sign_up', to: 'users#new'
  get '/sign_in', to: 'sessions#new'
  post '/sign_in', to: 'sessions#create'
  delete '/sign_out', to: 'sessions#destroy'

end

app/models/raffle.rb
class Raffle < ApplicationRecord
    has_many :tickets
    has_many :users, through: :tickets
    attr_accessor :gold, :silver, :bronze

    def self.filter(filter)
        if filter
            raffle = Raffle.where(category: filter)
        else
            Raffle.all
        end
    end

    # def bid_tickets(tier)
    #     params[:raffle][:"tier"].to_i
    # end
    
    # def bid_total
    #     (bid_tickets(gold) * 3) + (bid_tickets(silver) * 2) + bid_tickets(bronze)
    # end

    def current_bids
        (self.tickets.all_gold.count*3) + (self.tickets.all_silver.count*2) + (self.tickets.all_bronze.count)
    end

    def enough_slots?
        bid_total + current_bids > self.number_of_ticket_slots 
    end
  
    def current_tickets(user, tier)
        user.tickets.where(tier: tier, raffle_id: self.id).count
    end

    def update_tickets(user, gold, silver, bronze)
        gold.times {user.tickets.find_by(tier: 'gold', used: false).update(:used => true, :raffle_id => self.id)}
        silver.times {user.tickets.find_by(tier: 'silver', used: false).update(:used => true, :raffle_id => self.id)}
        bronze.times {user.tickets.find_by(tier: 'bronze', used: false).update(:used => true, :raffle_id => self.id)}
        @@raff_arr = []
        @@raff_arr.fill(user.username, @@raff_arr.size, gold*3)
        @@raff_arr.fill(user.username, @@raff_arr.size, silver*2)
        @@raff_arr.fill(user.username, @@raff_arr.size, bronze )
    end

    def enough_slots?
        bid_total + current_bids > self.number_of_ticket_slots 
    end

    def slots_filled?
        self.number_of_ticket_slots == current_bids
    end

    def select_winner
        @winner = @@raff_arr.sample
        self.update(winner: @winner)
       #code to ship item to winner using amazon api
       Raffle.create(product_name: self.product_name, product_description: self.product_description, product_image: self.product_image, category: self.category, number_of_ticket_slots: self.number_of_ticket_slots)
    end

end

app/controllers/raffles_controller.rb
class RafflesController < ApplicationController
  before_action :set_raffle, only: [:show, :edit, :update]
 
    def index
      @raffles = Raffle.filter(params[:filter]).where(winner: nil)
    end

    def new
        @raffle = Raffle.new
    end
    
    def show
        redirect_to edit_raffle_path
    end
    
    def create
        @raffle = Raffle.new(raffle_params)
        if @raffle.save
          redirect_to raffle_path(@raffle)
        else
          render :new
        end
    end
    
    def edit
    end
    
    def update
      bid_gold = params[:raffle][:gold].to_i
      bid_silver = params[:raffle][:silver].to_i
      bid_bronze = params[:raffle][:bronze].to_i
      bid_total = (bid_gold*3)+(bid_silver*2)+(bid_bronze)
      if bid_gold > current_user.user_gold || bid_silver > current_user.user_silver || bid_bronze > current_user.user_bronze
        redirect_to edit_raffle_path, notice: "You do not have enough tickets."
      else 
        if bid_total + @raffle.current_bids > @raffle.number_of_ticket_slots    
        redirect_to edit_raffle_path, notice: "There aren't enough spots left in this raffle to handle your entry! Please use less tickets."
        else @raffle.update_tickets(current_user, bid_gold, bid_silver, bid_bronze)
          if @raffle.slots_filled?
          @raffle.select_winner
          end
        end
       redirect_to edit_raffle_path(@raffle)
      end
    end

    def delete
      params[:filter].clear
    end

    private 

    def raffle_params
      params.require(:raffle).permit(:product_name, :product_description, :product_image, :number_of_ticket_slots, :filter)
    end
    
    def set_raffle
      @raffle = Raffle.find(params[:id])
    end

    def filtering_params(params)
      params.slice(:category)
    end   
  
end

app/helpers/raffles_helper.rb
module RafflesHelper

    

end

app/views/raffles/edit.html.erb
<div class="container">
<p><strong>Product</strong></p>
<p><%= @raffle.product_name %></p>
<br>
<p> <% if @raffle.winner%>
<b><%=@raffle.winner%> has won this raffle!</b>
<%end%></p> <br>
<p><img style='width:30%' src="<%= @raffle.product_image%>"></p>
<br>
<p><strong>Product Description</strong></p>
<p><%= @raffle.product_description %></p>
<br>
<p><strong>Spots Left</strong></p>
<p><%= @raffle.current_bids%> / <%= @raffle.number_of_ticket_slots %>

<p>Use Tickets:</p><br>
<%= form_for(@raffle) do |f| %>
  <%=f.label :ticket, "Gold" %>: <br>
  <%= image_tag "gold.jpg", class: "small_ticket" %><br>
  <%=f.number_field :gold%><br>
  <%=f.label :ticket, "Silver" %>:<br>
  <%= image_tag "silver.jpg", class: "small_ticket" %><br>
  <%=f.number_field :silver %><br>
  <%=f.label :ticket, "Bronze" %>:<br>
  <%= image_tag "bronze.jpg", class: "small_ticket" %><br>
  <%=f.number_field :bronze %> <br><br>
  <%= f.submit "Use Tickets" %>
<% end %><br>

<p>Your Entries:</p>

 <div>
        Gold:<%= image_tag "gold.jpg", class: "small_ticket" %> <%=current_user.user_gold%>
        Silver:<%= image_tag "silver.jpg", class: "small_ticket" %> <%=current_user.user_silver%>
        Bronze: <%= image_tag "bronze.jpg", class: "small_ticket" %><%=current_user.user_bronze%></div></div>

app/views/raffles/index.html.erb
<br><br><br>
<div class="title">Current Raffles:</div>
<div class="container">
<%= form_tag(raffles_path, method: 'get') do %>
  <%= select_tag(:filter, options_for_select(Raffle.pluck(:category).uniq, params[:filter])) %>
  <%= submit_tag ("Filter"), class: 'button' %> 
<% end %>
<a href="/raffles"><button class="button">Clear</button></a>
</div></div>
    <% @raffles.each do |raffle| %>
    <div class="container">
        <p><strong>Product</strong></p>
        <p> <% if raffle.winner%>
        <b><%=raffle.winner%> has won this raffle!</b>
        <% end %>
        <p><%= raffle.product_name %></p>
        <br>
        <p><img src="<%= raffle.product_image%>"></p>
        <br>
        <p><strong>Product Description</strong></p>
        <p><%= raffle.product_description %></p>
        <br>
        <p><strong>Spots Left</strong></p>
        <p><%= raffle.current_bids %> / <%= raffle.number_of_ticket_slots %>
        <br>
        <%= link_to "Enter", edit_raffle_path(raffle), class: "nav-item2" %></p>
        </div>
    <% end %>

<br><br><br>