config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  resources :raffles, :path_names => {:edit => 'enter' }
  resources :tickets, :path_names => {:edit => 'claim' }

  resources :raffles do
    resources :users, only: [:index]
  end

  resources :user do
    resources :tickets, only: [:new]
  end

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  root 'welcome#home'
  get '/sign_up', to: 'users#new'
  get '/sign_in', to: 'sessions#new'
  post '/sign_in', to: 'sessions#create'
  delete '/sign_out', to: 'sessions#destroy'

end

app/models/ticket.rb
class Ticket < ApplicationRecord
    belongs_to :user
    belongs_to :raffle, optional: true
    attr_accessor :gold, :silver, :bronze
    scope :gold, -> { find_by(tier: 'gold') }
    scope :silver, -> { find_by(tier: 'silver') }
    scope :bronze, -> { find_by(tier: 'bronze') }
    scope :unused, -> { where(used: false)}
    scope :all_gold, -> { where(tier: 'gold') }
    scope :all_silver, -> { where(tier: 'silver') }
    scope :all_bronze, -> { where(tier: 'bronze') }
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
   def new
      @ticket = Ticket.new
      @user = current_user
   end

   def index
        @user = current_user
        @tickets = @user.tickets
   end

   def edit
      @ticket = Ticket.new
      @tickets = current_user.tickets.all
   end

   def update
      params[:user][:gold].to_i.times {Ticket.create(:user_id => current_user.id, :tier => 'gold', :used => false)}
      params[:user][:silver].to_i.times {Ticket.create(:user_id => current_user.id, :tier => 'silver', :used => false)}
      params[:user][:bronze].to_i.times {Ticket.create(:user_id => current_user.id, :tier => 'bronze', :used => false)}
      redirect_to root_url
   end
   
   def ticket_count(tier)
      params[:ticket][tier].to_i
   end

   def ticket_create(tier)
      @tier = tier
      Ticket.create(:user_id => current_user.id, :tier => @tier, :used => false)
   end

   
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/new.html.erb
<br><div class="container">
<div class="title">Get Tickets:</div><br>

<%= form_for(@user, url: new_ticket_path) do |f| %>
  <%=f.label :tier, "Gold" %>: <br>
  <%= image_tag "gold.jpg", class: "medium_ticket" %><br>
  <%=f.number_field :gold %><br>
  <%=f.label :tier, "Silver" %>:<br>
  <%= image_tag "silver.jpg",class: "medium_ticket" %><br>
  <%=f.number_field :silver %><br>
  <%=f.label :tier, "Bronze" %>:<br>
  <%= image_tag "bronze.jpg", class: "medium_ticket" %><br>
  <%=f.number_field :bronze %> <br><br>
  <%= f.submit "Get Tickets" %>
<% end %></div>