config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  resources :raffles, :path_names => {:edit => 'enter' }
  resources :tickets, :path_names => {:edit => 'claim' }

  resources :raffles do
    resources :users, only: [:index]
  end

  resources :user do
    resources :tickets, only: [:new]
  end

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  root 'welcome#home'
  get '/sign_up', to: 'users#new'
  get '/sign_in', to: 'sessions#new'
  post '/sign_in', to: 'sessions#create'
  delete '/sign_out', to: 'sessions#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if @user && @user.username != nil%>
    <% current_user.raffles.where(winner: current_user.username, updated_at: 5.minutes.ago) != "" %>
    <p>Attention! You have recently won a raffle. Please check your raffle history.</p>   
  <%end%>
  <% if current_user %>
  <div class="topnav" id="">
        <div class="nav-item ">
         <%= link_to "Home", root_url %>
        </div >
        <div class="nav-item ">
          <%= link_to "Profile", edit_registration_path(current_user) %>
        </div >
        <div class="nav-item ">
          <%= link_to "History", raffle_users_path(current_user) %>
        </div >
         <div class="nav-item ">
          <%= link_to "Tickets", new_user_ticket_path(current_user) %>
        </div >
        <div class="nav-item ">
          <%= link_to "Sign Out",  destroy_user_session_path, method: :delete %>
        </div >
    

        <div class="profile_item">
        <div class="user" style="margin-right:10%">
          <%= current_user.username%> 
        </div><br>
        <div class="user">
          Tickets: <%= image_tag "gold.jpg", class: "small_ticket" %>Gold (3 Entries) - <%=current_user.user_gold%> | <%= image_tag "silver.jpg", class: "small_ticket" %> Silver (2 Entries) - <%=current_user.user_silver%> | <%= image_tag "bronze.jpg", class: "small_ticket" %> Bronze (1 Entry) - <%=current_user.user_bronze%>
        </div>
      </ul>
      <%= image_tag "logo.jpg", class: "container3"%>
    </div> </div >
   
    <%end%>
    
    <% if notice %>
  <div class="alert" style="color:white"><%= notice %></p>
<% end %>
<% if alert %>
  <div class="alert" style="color:white"><%= alert %></div>
<% end %>

    <%= yield %>


  <div class="footer"><br><div class="container">
   <a href="https://github.com/ianhutson"> Contact Us</a></div><br>
  </footer>
  </body>
</html>